name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    
    services:
      postgres:
        image: postgres
        ports:
          -  5432:5432       
      nats:
        image: nats
        ports: 
          - 6222:6222
          - 4222:4222
          - 8222:8222

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Erlang/Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.3
          elixir-version: 1.9.2

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - run: mix deps.get
      - name: Run tests
        run: mix test
        env:
          DB_NAME: wasmdome
          DB_USER: postgres
          DB_PASS: postgres
          DB_HOST: localhost  
